# Site Info
title: Jin`s blog
tagline: 'Study for Data Science'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: https://jin717.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jin
  description: <strong>데이터가 삶에 의미 있기를</strong>
  gravatar:  # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/jin717
    # facebook:  <hide>
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:     wlsgur717@naver.com

    # Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog/'
  Categories:           
    - '/'
    - { Machine learning: '/blog/categories/#machine_learning'}
    - { Deep learning: '/blog/categories/#deep_learning'}
    - { Statistics: '/blog/categories/#statistics'}
    - { Papers: '/blog/categories/#papers' }
    - { Data engineering: '/blog/categories/#data_engineering' }
    - { Algorithm: '/blog/categories/#algorithm' }
    - { Devops: '/blog/categories/#devops'}
    - { Categories: '/blog/categories/' }
    - { Others: '/blog/categories/#others' }

    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/jin717?tab=repositories'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'



# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'jin-blog' # leave blank if you don't want disqus

plugins: 
  [jekyll-paginate]
